// Database functions to interact with food data
window.foodData = [
  {
    name: "Arroz cocido",
    group: "Cereales",
    measure: "g",
    serving: 47,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 26,
    calcium: 1.4,
    iron: 0.7,
    potasium: 13.5,
    sodium: 0,
  },
  {
    name: "Arroz integral cocido",
    group: "Cereales",
    measure: "g",
    serving: 65,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 2.6,
    calcium: 6.7,
    iron: 0.3,
    potasium: 51.4,
    sodium: 0.7,
  },
  {
    name: "Avena en hojuelas",
    group: "Cereales",
    measure: "g",
    serving: 20,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 0,
    calcium: 10.4,
    iron: 0.8,
    potasium: 70,
    sodium: 0.8,
  },
  {
    name: "Bolillo sin migajón",
    group: "Cereales",
    measure: "g",
    serving: 30,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 0,
    calcium: 12.6,
    iron: 0.4,
    potasium: 33.6,
    sodium: 170.7,
  },
  {
    name: "Elote blanco cocido",
    group: "Cereales",
    measure: "g",
    serving: 82,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 6.5,
    folicAcid: 37.5,
    calcium: 1.6,
    iron: 0.4,
    potasium: 220.1,
    sodium: 12.2,
  },
  {
    name: "Espagueti cocido",
    group: "Cereales",
    measure: "g",
    serving: 46,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 2.3,
    calcium: 6.9,
    iron: 0.5,
    potasium: 20.3,
    sodium: 1.4,
  },
  {
    name: "Papa cocida",
    group: "Cereales",
    measure: "g",
    serving: 68,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 0,
    vitaminC: 9.1,
    folicAcid: 7.1,
    calcium: 3.5,
    iron: 0.2,
    potasium: 257.9,
    sodium: 2.5,
  },
  {
    name: "Tortilla de maíz",
    group: "Cereales",
    measure: "g",
    serving: 30,
    carbs: 15,
    protein: 2,
    fat: 0,
    vitaminA: 6,
    vitaminC: 0,
    folicAcid: 0,
    calcium: 58.8,
    iron: 0.8,
    potasium: 0,
    sodium: 0,
  },
  {
    name: "Frijol cocido",
    group: "Leguminosas",
    measure: "g",
    serving: 86,
    carbs: 20,
    protein: 8,
    fat: 1,
    vitaminA: 5.2,
    vitaminC: 0,
    folicAcid: 128.1,
    calcium: 23.2,
    iron: 1.8,
    potasium: 305.3,
    sodium: 1,
  },
  {
    name: "Garbanzo cocido",
    group: "Leguminosas",
    measure: "g",
    serving: 82,
    carbs: 20,
    protein: 8,
    fat: 1,
    vitaminA: 2.5,
    vitaminC: 1,
    folicAcid: 141,
    calcium: 40,
    iron: 2.4,
    potasium: 238.5,
    sodium: 5.5,
  },
  {
    name: "Lenteja cocida",
    group: "Leguminosas",
    measure: "g",
    serving: 99,
    carbs: 20,
    protein: 8,
    fat: 1,
    vitaminA: 1,
    vitaminC: 1.5,
    folicAcid: 179,
    calcium: 19,
    iron: 3.3,
    potasium: 365.5,
    sodium: 2,
  },
  {
    name: "Manzana verde",
    group: "Frutas",
    measure: "g",
    serving: 71,
    carbs: 15,
    protein: 0,
    fat: 0,
    sodium: 0,
  },
  {
    name: "Melón Picado",
    group: "Frutas",
    measure: "g",
    serving: 160,
    carbs: 15,
    protein: 0,
    fat: 0,
    sodium: 14.4,
  },
  {
    name: "Plátano ",
    group: "Frutas",
    measure: "g",
    serving: 54,
    carbs: 15,
    protein: 0,
    fat: 0,
    sodium: 0.5,
  },
  {
    name: "Sandía picada",
    group: "Frutas",
    measure: "g",
    serving: 71,
    carbs: 15,
    protein: 0,
    fat: 0,
    vitaminA: 59,
    vitaminC: 15,
    folicAcid: 4,
    calcium: 13,
    iron: 0.3,
    potasium: 186,
    sodium: 3,
  },
  {
    name: "Bistec de res",
    group: "OAMBA",
    measure: "g",
    serving: 30,
    carbs: 0,
    protein: 7,
    fat: 1,
    vitaminA: 41.7,
    vitaminC: 0,
    folicAcid: 3,
    calcium: 2.7,
    iron: 0.5,
    potasium: 90,
    sodium: 18,
  },
  {
    name: "Camarones crudos",
    group: "OAMBA",
    measure: "g",
    serving: 36,
    carbs: 0,
    protein: 7,
    fat: 1,
    vitaminA: 19.5,
    vitaminC: 0.7,
    folicAcid: 1.1,
    calcium: 18.6,
    iron: 0.9,
    potasium: 66.5,
    sodium: 53.4,
  },
  {
    name: "Cecina",
    group: "OAMBA",
    measure: "g",
    serving: 25,
    carbs: 0,
    protein: 7,
    fat: 1,
    vitaminA: 0.6,
    vitaminC: 0,
    folicAcid: 0,
    calcium: 8.8,
    iron: 1.1,
    potasium: 85,
    sodium: 275,
  },
  {
    name: "Claras de huevo",
    group: "OAMBA",
    measure: "g",
    serving: 66,
    carbs: 0,
    protein: 7,
    fat: 1,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 2.6,
    calcium: 4.6,
    iron: 0.1,
    potasium: 107.6,
    sodium: 109.6,
  },
  {
    name: "Pechuga de pollo cocida",
    group: "OAMBA",
    measure: "g",
    serving: 30,
    carbs: 0,
    protein: 7,
    fat: 1,
    vitaminA: 2.4,
    vitaminC: 0,
    folicAcid: 0.9,
    calcium: 3.9,
    iron: 0.3,
    potasium: 54,
    sodium: 19.5,
  },
  {
    name: "Arrachera cocida",
    group: "OABA",
    measure: "g",
    serving: 30,
    carbs: 0,
    protein: 7,
    fat: 3,
    vitaminA: 0,
    vitaminC: 0,
    folicAcid: 2.7,
    calcium: 5.4,
    iron: 0.5,
    potasium: 105,
    sodium: 17.1,
  },
  {
    name: "Atún en agua Tuny lata jumbo",
    group: "Ultraprocesados",
    measure: 'g',
    serving: 100,
    package: 220,
    carbs: 0,
    protein: 21,
    fat: 1,
    sodium: 260,
  },
  {
    name: "Fuze Tea Té verde y sabor a limón de 600ml",
    group: "Ultraprocesados",
    measure: 'ml',
    serving: 100,
    package: 600,
    carbs: 6.5,
    protein: 0,
    fat: 0,
    sodium: 9,
  },
  {
    name: "Peñafiel Twist",
    group: "Ultraprocesados",
    measure: 'ml',
    serving: 100,
    package: 600,
    carbs: 0,
    protein: 0,
    fat: 0,
    sodium: 67,
  },
];
