// Database functions to interact with food data
window.foodData = [
  {
    name: "Fuze Tea Té verde y sabor a limón de 600ml",
    group: "Ultraprocessed",
    measure: 'ml',
    serving: 100,
    package: 600,
    carbs: 6.5,
    protein: 0,
    fat: 0,
    sodium: 9,
  },
  {
    name: "Atún en agua Tuny lata jumbo",
    group: "Ultraprocessed",
    measure: 'g',
    serving: 100,
    package: 220,
    carbs: 0,
    protein: 21,
    fat: 1,
    sodium: 260,
  },
  {
    name: "Chicken Breast",
    group: "Proteins",
    measure: 'g',
    serving: 100,
    package: 500,
    carbs: 0,
    protein: 31,
    fat: 3.6,
    sodium: 50,
  },
  {
    name: "Tofu",
    group: "Proteins",
    measure: 'g',
    serving: 100,
    package: 400,
    carbs: 1.9,
    protein: 8,
    fat: 4.8,
    sodium: 7,
  },
];
